import type * as cheerio from 'cheerio';
import { CaptionTrack, TranscriptSegment, OutputItem } from './types.js';
import { YOUTUBE } from './constants.js';

/**
 * Extract ytInitialPlayerResponse from YouTube video page.
 * Contains video metadata and caption track info.
 */
export function extractPlayerResponse($: cheerio.CheerioAPI): Record<string, any> | null {
    const html = $.html();

    // Try script variable first
    const varMatch = html.match(/var\s+ytInitialPlayerResponse\s*=\s*({.+?})\s*;/s);
    if (varMatch) {
        try { return JSON.parse(varMatch[1]); } catch { /* continue */ }
    }

    // Try alternative pattern (sometimes it's assigned differently)
    const altMatch = html.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/s);
    if (altMatch) {
        try { return JSON.parse(altMatch[1]); } catch { /* continue */ }
    }

    return null;
}

/**
 * Extract ytInitialData from YouTube page.
 * Contains page-level data (playlist items, search results, channel videos).
 */
export function extractInitialData($: cheerio.CheerioAPI): Record<string, any> | null {
    const html = $.html();

    const match = html.match(/var\s+ytInitialData\s*=\s*({.+?})\s*;/s);
    if (match) {
        try { return JSON.parse(match[1]); } catch { /* continue */ }
    }

    const altMatch = html.match(/ytInitialData\s*=\s*({.+?})\s*;/s);
    if (altMatch) {
        try { return JSON.parse(altMatch[1]); } catch { /* continue */ }
    }

    return null;
}

/**
 * Extract available caption tracks from player response.
 */
export function extractCaptionTracks(playerResponse: Record<string, any>): CaptionTrack[] {
    const captions = playerResponse?.captions?.playerCaptionsTracklistRenderer;
    if (!captions?.captionTracks) return [];

    return captions.captionTracks.map((track: any) => ({
        baseUrl: track.baseUrl,
        languageCode: track.languageCode,
        name: track.name?.simpleText ?? track.name?.runs?.[0]?.text ?? track.languageCode,
        kind: track.kind, // 'asr' for auto-generated
        isTranslatable: track.isTranslatable ?? false,
    }));
}

/**
 * Extract video metadata from player response.
 */
export function extractVideoMetadata(playerResponse: Record<string, any>): {
    title: string | null;
    channelName: string | null;
    channelUrl: string | null;
    description: string | null;
    viewCount: number | null;
    likeCount: number | null;
    publishDate: string | null;
    duration: string | null;
    thumbnailUrl: string | null;
} {
    const videoDetails = playerResponse?.videoDetails;
    const microformat = playerResponse?.microformat?.playerMicroformatRenderer;

    if (!videoDetails) {
        return {
            title: null, channelName: null, channelUrl: null,
            description: null, viewCount: null, likeCount: null,
            publishDate: null, duration: null, thumbnailUrl: null,
        };
    }

    const durationSecs = parseInt(videoDetails.lengthSeconds || '0');
    const hours = Math.floor(durationSecs / 3600);
    const mins = Math.floor((durationSecs % 3600) / 60);
    const secs = durationSecs % 60;
    const durationStr = hours > 0
        ? `${hours}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`
        : `${mins}:${String(secs).padStart(2, '0')}`;

    const thumbnails = videoDetails.thumbnail?.thumbnails ?? [];
    const bestThumb = thumbnails[thumbnails.length - 1]?.url ?? null;

    return {
        title: videoDetails.title ?? null,
        channelName: videoDetails.author ?? null,
        channelUrl: microformat?.ownerProfileUrl
            ? `https://www.youtube.com${microformat.ownerProfileUrl}`
            : videoDetails.channelId
                ? `https://www.youtube.com/channel/${videoDetails.channelId}`
                : null,
        description: videoDetails.shortDescription ?? null,
        viewCount: videoDetails.viewCount ? parseInt(videoDetails.viewCount) : null,
        likeCount: null, // Not in playerResponse, would need ytInitialData
        publishDate: microformat?.publishDate ?? microformat?.uploadDate ?? null,
        duration: durationStr,
        thumbnailUrl: bestThumb,
    };
}

/**
 * Select the best caption track based on user preferences.
 */
export function selectCaptionTrack(
    tracks: CaptionTrack[],
    preferredLanguage: string,
    includeAutoGenerated: boolean,
): CaptionTrack | null {
    if (tracks.length === 0) return null;

    // 1. Try exact match for preferred language (manual captions first)
    const manualExact = tracks.find(
        (t) => t.languageCode === preferredLanguage && t.kind !== 'asr'
    );
    if (manualExact) return manualExact;

    // 2. Try auto-generated for preferred language (if allowed)
    if (includeAutoGenerated) {
        const autoExact = tracks.find(
            (t) => t.languageCode === preferredLanguage && t.kind === 'asr'
        );
        if (autoExact) return autoExact;
    }

    // 3. Try language prefix match (e.g., 'en' matches 'en-US')
    const prefixMatch = tracks.find(
        (t) => t.languageCode.startsWith(preferredLanguage) &&
            (includeAutoGenerated || t.kind !== 'asr')
    );
    if (prefixMatch) return prefixMatch;

    // 4. Fall back to any manual caption
    const anyManual = tracks.find((t) => t.kind !== 'asr');
    if (anyManual) return anyManual;

    // 5. Fall back to any auto-generated (if allowed)
    if (includeAutoGenerated) {
        return tracks[0] ?? null;
    }

    return null;
}

/**
 * Parse XML transcript response into segments.
 */
export function parseTranscriptXml($: cheerio.CheerioAPI): TranscriptSegment[] {
    const segments: TranscriptSegment[] = [];

    $('text').each((_, el) => {
        const $el = $(el);
        const start = parseFloat($el.attr('start') ?? '0');
        const duration = parseFloat($el.attr('dur') ?? '0');
        // Decode HTML entities and clean text
        let text = $el.text()
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&quot;/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/\n/g, ' ')
            .trim();

        if (text) {
            segments.push({ text, start, duration });
        }
    });

    return segments;
}

/**
 * Build translation URL for a caption track.
 * YouTube can auto-translate captions to many languages.
 */
export function buildTranslationUrl(track: CaptionTrack, targetLanguage: string): string {
    const url = new URL(track.baseUrl);
    url.searchParams.set('tlang', targetLanguage);
    return url.toString();
}

/**
 * Convert transcript segments to full plain text.
 */
export function segmentsToPlainText(segments: TranscriptSegment[]): string {
    return segments.map((s) => s.text).join(' ');
}

/**
 * Convert transcript segments to SRT format.
 */
export function segmentsToSrt(segments: TranscriptSegment[]): string {
    return segments.map((seg, i) => {
        const startTime = formatSrtTime(seg.start);
        const endTime = formatSrtTime(seg.start + seg.duration);
        return `${i + 1}\n${startTime} --> ${endTime}\n${seg.text}\n`;
    }).join('\n');
}

/**
 * Convert transcript segments to VTT format.
 */
export function segmentsToVtt(segments: TranscriptSegment[]): string {
    const header = 'WEBVTT\n\n';
    const body = segments.map((seg) => {
        const startTime = formatVttTime(seg.start);
        const endTime = formatVttTime(seg.start + seg.duration);
        return `${startTime} --> ${endTime}\n${seg.text}\n`;
    }).join('\n');
    return header + body;
}

/** Format seconds to SRT timestamp: HH:MM:SS,mmm */
function formatSrtTime(totalSeconds: number): string {
    const hours = Math.floor(totalSeconds / 3600);
    const mins = Math.floor((totalSeconds % 3600) / 60);
    const secs = Math.floor(totalSeconds % 60);
    const ms = Math.round((totalSeconds % 1) * 1000);
    return `${String(hours).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
}

/** Format seconds to VTT timestamp: HH:MM:SS.mmm */
function formatVttTime(totalSeconds: number): string {
    return formatSrtTime(totalSeconds).replace(',', '.');
}

/**
 * Extract video IDs from a playlist page's ytInitialData.
 */
export function extractPlaylistVideoIds(initialData: Record<string, any>): string[] {
    const ids: string[] = [];

    try {
        const contents = initialData?.contents?.twoColumnBrowseResultsRenderer?.tabs?.[0]
            ?.tabRenderer?.content?.sectionListRenderer?.contents?.[0]
            ?.itemSectionRenderer?.contents?.[0]
            ?.playlistVideoListRenderer?.contents ?? [];

        for (const item of contents) {
            const videoId = item?.playlistVideoRenderer?.videoId;
            if (videoId) ids.push(videoId);
        }
    } catch { /* failed to parse */ }

    return ids;
}

/**
 * Extract video IDs from search results.
 */
export function extractSearchVideoIds(initialData: Record<string, any>): string[] {
    const ids: string[] = [];

    try {
        const contents = initialData?.contents?.twoColumnSearchResultsRenderer
            ?.primaryContents?.sectionListRenderer?.contents ?? [];

        for (const section of contents) {
            const items = section?.itemSectionRenderer?.contents ?? [];
            for (const item of items) {
                const videoId = item?.videoRenderer?.videoId;
                if (videoId) ids.push(videoId);
            }
        }
    } catch { /* failed to parse */ }

    return ids;
}

/**
 * Extract video IDs from a channel's videos tab.
 */
export function extractChannelVideoIds(initialData: Record<string, any>): string[] {
    const ids: string[] = [];

    try {
        // Try tabs (channel page)
        const tabs = initialData?.contents?.twoColumnBrowseResultsRenderer?.tabs ?? [];
        for (const tab of tabs) {
            const tabContent = tab?.tabRenderer?.content ?? tab?.expandableTabRenderer?.content;
            if (!tabContent) continue;

            const items = tabContent?.richGridRenderer?.contents ??
                tabContent?.sectionListRenderer?.contents?.[0]?.itemSectionRenderer?.contents ?? [];

            for (const item of items) {
                const videoId = item?.richItemRenderer?.content?.videoRenderer?.videoId
                    ?? item?.gridVideoRenderer?.videoId;
                if (videoId) ids.push(videoId);
            }
        }
    } catch { /* failed to parse */ }

    return ids;
}
