import { Actor, log } from 'apify';
import { createCheerioRouter, Dataset, type CheerioAPI } from 'crawlee';
import { LABELS, YOUTUBE, BLOCK_KEYWORDS, PATTERNS } from './constants.js';
import {
    extractPlayerResponse,
    extractInitialData,
    extractCaptionTracks,
    extractVideoMetadata,
    selectCaptionTrack,
    parseTranscriptXml,
    buildTranslationUrl,
    segmentsToPlainText,
    segmentsToSrt,
    segmentsToVtt,
    extractPlaylistVideoIds,
    extractSearchVideoIds,
    extractChannelVideoIds,
} from './extractors.js';
import { getState, incrementItems, hasReachedLimit, isDuplicate } from './state.js';
import { Input, OutputItem, TranscriptSegment } from './types.js';

export const router = createCheerioRouter();

// Input is injected from main.ts via userData
function getInput(userData: Record<string, unknown>): Input {
    return (userData.input as Input) ?? {};
}

// --- Block detection ---
function checkForBlock($: any, session: any): void {
    const title = $('title').text();
    for (const keyword of BLOCK_KEYWORDS.TITLE) {
        if (title.includes(keyword)) {
            session?.markBad();
            throw new Error(`Blocked: "${keyword}"`);
        }
    }
    session?.markGood();
}

// --- VIDEO handler: extract transcript from a single video page ---
router.addHandler(LABELS.VIDEO, async ({ request, $, sendRequest, log, session }) => {
    const input = getInput(request.userData);
    const maxItems = input.maxItems ?? 0;

    if (hasReachedLimit(maxItems)) {
        log.info('Max items reached, skipping.');
        return;
    }

    checkForBlock($, session);

    // Extract video ID from URL
    const videoIdMatch = request.url.match(PATTERNS.VIDEO_ID);
    const videoId = videoIdMatch?.[1];
    if (!videoId) {
        log.warning(`Could not extract video ID from ${request.url}`);
        return;
    }

    if (isDuplicate(videoId)) {
        log.debug(`Duplicate video: ${videoId}, skipping.`);
        return;
    }

    // Extract player response (contains caption tracks + metadata)
    const playerResponse = extractPlayerResponse($);
    if (!playerResponse) {
        log.warning(`No player response found for ${request.url}. Video may be private or unavailable.`);
        await Dataset.pushData({
            url: request.url,
            videoId,
            title: null,
            transcript: null,
            fullText: null,
            '#isFailed': true,
            '#errorMessage': 'Could not extract player response. Video may be private, age-restricted, or unavailable.',
            scrapedAt: new Date().toISOString(),
        });
        return;
    }

    // Check playability
    const playabilityStatus = playerResponse.playabilityStatus?.status;
    if (playabilityStatus === 'LOGIN_REQUIRED' || playabilityStatus === 'ERROR' || playabilityStatus === 'UNPLAYABLE') {
        const reason = playerResponse.playabilityStatus?.reason ?? playabilityStatus;
        log.warning(`Video ${videoId} is not accessible: ${reason}`);
        await Dataset.pushData({
            url: request.url,
            videoId,
            title: playerResponse.videoDetails?.title ?? null,
            transcript: null,
            fullText: null,
            '#isFailed': true,
            '#errorMessage': `Video not accessible: ${reason}`,
            scrapedAt: new Date().toISOString(),
        });
        return;
    }

    // Extract metadata
    const metadata = input.includeVideoMetadata !== false
        ? extractVideoMetadata(playerResponse)
        : { title: playerResponse.videoDetails?.title ?? null, channelName: null, channelUrl: null, description: null, viewCount: null, likeCount: null, publishDate: null, duration: null, thumbnailUrl: null };

    // Extract caption tracks
    const captionTracks = extractCaptionTracks(playerResponse);
    const availableLanguages = captionTracks.map((t) =>
        `${t.languageCode}${t.kind === 'asr' ? ' (auto)' : ''}`
    );

    if (captionTracks.length === 0) {
        log.info(`No captions available for video ${videoId}: "${metadata.title}"`);
        const result: OutputItem = {
            url: request.url,
            videoId,
            ...metadata,
            language: input.language ?? 'en',
            languageName: '',
            isAutoGenerated: false,
            isTranslated: false,
            availableLanguages: [],
            transcript: null,
            fullText: null,
            formattedTranscript: null,
            segmentCount: 0,
            totalDurationSecs: 0,
            scrapedAt: new Date().toISOString(),
        };
        incrementItems();
        await Dataset.pushData(result);
        await Actor.setStatusMessage(`Scraped ${getState().itemsScraped} videos`);
        return;
    }

    // Select best caption track
    const preferredLang = input.language ?? 'en';
    const includeAuto = input.includeAutoGenerated !== false; // default true
    const selectedTrack = selectCaptionTrack(captionTracks, preferredLang, includeAuto);

    if (!selectedTrack) {
        log.warning(`No matching captions for language "${preferredLang}" on video ${videoId}`);
        const result: OutputItem = {
            url: request.url,
            videoId,
            ...metadata,
            language: preferredLang,
            languageName: '',
            isAutoGenerated: false,
            isTranslated: false,
            availableLanguages,
            transcript: null,
            fullText: null,
            formattedTranscript: null,
            segmentCount: 0,
            totalDurationSecs: 0,
            scrapedAt: new Date().toISOString(),
        };
        incrementItems();
        await Dataset.pushData(result);
        return;
    }

    // Determine if we need translation
    let transcriptUrl = selectedTrack.baseUrl;
    let isTranslated = false;
    const translationLang = input.translationLanguage;

    if (translationLang && translationLang !== selectedTrack.languageCode && selectedTrack.isTranslatable) {
        transcriptUrl = buildTranslationUrl(selectedTrack, translationLang);
        isTranslated = true;
    }

    // Ensure we get XML format (not JSON3)
    const url = new URL(transcriptUrl);
    url.searchParams.set('fmt', 'srv3');
    transcriptUrl = url.toString();

    // Fetch the transcript XML
    let segments: TranscriptSegment[] = [];
    try {
        const transcriptResponse = await sendRequest({
            url: transcriptUrl,
            headers: {
                'Accept-Language': 'en-US,en;q=0.9',
                'Cookie': `SOCS=${YOUTUBE.CONSENT_COOKIE}`,
            },
        });
        const transcriptHtml = transcriptResponse.body as string;
        const cheerio = await import('cheerio');
        const $xml = cheerio.load(transcriptHtml, { xmlMode: true });
        segments = parseTranscriptXml($xml);
    } catch (err) {
        log.warning(`Failed to fetch transcript for ${videoId}: ${(err as Error).message}`);
    }

    // Build output
    const includeTimestamps = input.includeTimestamps !== false; // default true
    const outputFormat = input.outputFormat ?? 'json';

    let formattedTranscript: string | null = null;
    if (outputFormat === 'srt') {
        formattedTranscript = segmentsToSrt(segments);
    } else if (outputFormat === 'vtt') {
        formattedTranscript = segmentsToVtt(segments);
    }

    const totalDuration = segments.length > 0
        ? segments[segments.length - 1].start + segments[segments.length - 1].duration
        : 0;

    const result: OutputItem = {
        url: request.url,
        videoId,
        ...metadata,
        language: isTranslated ? (translationLang ?? selectedTrack.languageCode) : selectedTrack.languageCode,
        languageName: selectedTrack.name,
        isAutoGenerated: selectedTrack.kind === 'asr',
        isTranslated,
        availableLanguages,
        transcript: outputFormat === 'json'
            ? (includeTimestamps ? segments : segments.map((s) => ({ text: s.text, start: s.start, duration: s.duration })))
            : null,
        fullText: segmentsToPlainText(segments),
        formattedTranscript,
        segmentCount: segments.length,
        totalDurationSecs: Math.round(totalDuration),
        scrapedAt: new Date().toISOString(),
    };

    // Strip metadata fields if not requested
    if (input.includeVideoMetadata === false) {
        delete (result as any).channelName;
        delete (result as any).channelUrl;
        delete (result as any).description;
        delete (result as any).viewCount;
        delete (result as any).likeCount;
        delete (result as any).publishDate;
        delete (result as any).duration;
        delete (result as any).thumbnailUrl;
    }

    incrementItems();
    await Dataset.pushData(result);

    const state = getState();
    log.info(`[${state.itemsScraped}/${maxItems || '∞'}] Transcript: "${metadata.title}" (${segments.length} segments, ${selectedTrack.languageCode}${selectedTrack.kind === 'asr' ? ' auto' : ''})`);
    await Actor.setStatusMessage(`Scraped ${state.itemsScraped} transcripts`);
});

// --- PLAYLIST handler: discover videos in a playlist ---
router.addHandler(LABELS.PLAYLIST, async ({ request, $, log, session, crawler }) => {
    const input = getInput(request.userData);
    checkForBlock($, session);

    const initialData = extractInitialData($);
    if (!initialData) {
        log.warning(`Could not extract playlist data from ${request.url}`);
        return;
    }

    const videoIds = extractPlaylistVideoIds(initialData);
    log.info(`Found ${videoIds.length} videos in playlist: ${request.url}`);

    const requests = videoIds.map((id) => ({
        url: `${YOUTUBE.VIDEO_URL}${id}`,
        label: LABELS.VIDEO,
        userData: { input },
        uniqueKey: `video-${id}`,
    }));

    await crawler.addRequests(requests);
});

// --- CHANNEL handler: discover videos on a channel ---
router.addHandler(LABELS.CHANNEL, async ({ request, $, log, session, crawler }) => {
    const input = getInput(request.userData);
    checkForBlock($, session);

    const initialData = extractInitialData($);
    if (!initialData) {
        log.warning(`Could not extract channel data from ${request.url}`);
        return;
    }

    const videoIds = extractChannelVideoIds(initialData);
    log.info(`Found ${videoIds.length} videos on channel: ${request.url}`);

    const requests = videoIds.map((id) => ({
        url: `${YOUTUBE.VIDEO_URL}${id}`,
        label: LABELS.VIDEO,
        userData: { input },
        uniqueKey: `video-${id}`,
    }));

    await crawler.addRequests(requests);
});

// --- SEARCH handler: discover videos from search results ---
router.addHandler(LABELS.SEARCH, async ({ request, $, log, session, crawler }) => {
    const input = getInput(request.userData);
    checkForBlock($, session);

    const initialData = extractInitialData($);
    if (!initialData) {
        log.warning(`Could not extract search data from ${request.url}`);
        return;
    }

    const videoIds = extractSearchVideoIds(initialData);
    log.info(`Found ${videoIds.length} videos in search results for: "${request.userData.searchTerm}"`);

    const requests = videoIds.map((id) => ({
        url: `${YOUTUBE.VIDEO_URL}${id}`,
        label: LABELS.VIDEO,
        userData: { input },
        uniqueKey: `video-${id}`,
    }));

    await crawler.addRequests(requests);
});
