import { Actor, log } from 'apify';
import { createCheerioRouter } from 'crawlee';
import { LABELS, YOUTUBE, BLOCK_KEYWORDS, PATTERNS } from './constants.js';
import {
    fetchPlayerResponse,
    fetchTranscriptXml,
    extractPlayerResponseFromHtml,
    extractInitialData,
    extractCaptionTracks,
    extractVideoMetadata,
    selectCaptionTrack,
    parseTranscriptXml,
    buildTranslationUrl,
    segmentsToPlainText,
    segmentsToSrt,
    segmentsToVtt,
    extractPlaylistVideoIds,
    extractSearchVideoIds,
    extractChannelVideoIds,
} from './extractors.js';
import { getState, incrementItems, hasReachedLimit, isDuplicate } from './state.js';
import { Input, OutputItem, TranscriptSegment } from './types.js';

export const router = createCheerioRouter();

// Module-level input — set from main.ts to avoid userData bloat
let actorInput: Input = {};
export function setActorInput(input: Input): void { actorInput = input; }

function checkForBlock($: any, session: any): void {
    const title = $('title').text();
    for (const kw of BLOCK_KEYWORDS.TITLE) {
        if (title.includes(kw)) { session?.retire(); throw new Error(`Blocked: "${kw}"`); }
    }
    session?.markGood();
}

// --- VIDEO handler ---
router.addHandler(LABELS.VIDEO, async ({ request, $, log, session }) => {
    const input = actorInput;
    const maxItems = input.maxItems ?? 0;

    if (hasReachedLimit(maxItems)) return;
    checkForBlock($, session);

    const videoId = request.url.match(PATTERNS.VIDEO_ID)?.[1];
    if (!videoId) { log.warning(`No video ID in ${request.url}`); return; }
    if (isDuplicate(videoId)) { log.debug(`Duplicate: ${videoId}`); return; }

    // Use Android InnerTube API for working caption URLs
    let playerResponse = await fetchPlayerResponse(videoId);
    if (!playerResponse) {
        playerResponse = extractPlayerResponseFromHtml($ as any);
    }

    if (!playerResponse) {
        log.warning(`No player response for ${videoId}`);
        await Actor.pushData({ url: request.url, videoId, title: null, transcript: null, fullText: null, '#isFailed': true, '#errorMessage': 'Video unavailable', scrapedAt: new Date().toISOString() });
        return;
    }

    const status = playerResponse.playabilityStatus?.status;
    if (status === 'LOGIN_REQUIRED' || status === 'ERROR' || status === 'UNPLAYABLE') {
        const reason = playerResponse.playabilityStatus?.reason ?? status;
        log.warning(`Video ${videoId} not accessible: ${reason}`);
        await Actor.pushData({ url: request.url, videoId, title: playerResponse.videoDetails?.title ?? null, transcript: null, fullText: null, '#isFailed': true, '#errorMessage': reason, scrapedAt: new Date().toISOString() });
        return;
    }

    const metadata = input.includeVideoMetadata !== false ? extractVideoMetadata(playerResponse) : { title: playerResponse.videoDetails?.title ?? null, channelName: null, channelUrl: null, description: null, viewCount: null, likeCount: null, publishDate: null, duration: null, thumbnailUrl: null };

    const captionTracks = extractCaptionTracks(playerResponse);
    const availableLanguages = captionTracks.map((t: any) => `${t.languageCode}${t.kind === 'asr' ? ' (auto)' : ''}`);

    if (captionTracks.length === 0) {
        log.info(`No captions for ${videoId}: "${metadata.title}"`);
        incrementItems();
        await Actor.pushData({ url: request.url, videoId, ...metadata, language: input.language ?? 'en', languageName: '', isAutoGenerated: false, isTranslated: false, availableLanguages: [], transcript: null, fullText: null, formattedTranscript: null, segmentCount: 0, totalDurationSecs: 0, scrapedAt: new Date().toISOString() } as OutputItem);
        await Actor.setStatusMessage(`Scraped ${getState().itemsScraped} videos`);
        return;
    }

    const lang = input.language ?? 'en';
    const includeAuto = input.includeAutoGenerated !== false;
    const track = selectCaptionTrack(captionTracks, lang, includeAuto);

    if (!track) {
        log.warning(`No captions for lang "${lang}" on ${videoId}`);
        incrementItems();
        await Actor.pushData({ url: request.url, videoId, ...metadata, language: lang, languageName: '', isAutoGenerated: false, isTranslated: false, availableLanguages, transcript: null, fullText: null, formattedTranscript: null, segmentCount: 0, totalDurationSecs: 0, scrapedAt: new Date().toISOString() } as OutputItem);
        return;
    }

    let transcriptUrl = track.baseUrl;
    let isTranslated = false;
    if (input.translationLanguage && input.translationLanguage !== track.languageCode && track.isTranslatable) {
        transcriptUrl = buildTranslationUrl(track, input.translationLanguage);
        isTranslated = true;
    }

    let segments: TranscriptSegment[] = [];
    const xml = await fetchTranscriptXml(transcriptUrl);
    if (xml) {
        segments = parseTranscriptXml(xml);
    } else {
        log.warning(`Empty transcript response for ${videoId}`);
    }

    const fmt = input.outputFormat ?? 'json';
    let formattedTranscript: string | null = null;
    if (fmt === 'srt') formattedTranscript = segmentsToSrt(segments);
    else if (fmt === 'vtt') formattedTranscript = segmentsToVtt(segments);

    const totalDur = segments.length > 0 ? segments[segments.length - 1].start + segments[segments.length - 1].duration : 0;

    const result: OutputItem = {
        url: request.url,
        videoId,
        ...metadata,
        language: isTranslated ? (input.translationLanguage ?? track.languageCode) : track.languageCode,
        languageName: track.name,
        isAutoGenerated: track.kind === 'asr',
        isTranslated,
        availableLanguages,
        transcript: fmt === 'json' ? segments : null,
        fullText: segmentsToPlainText(segments),
        formattedTranscript,
        segmentCount: segments.length,
        totalDurationSecs: Math.round(totalDur),
        scrapedAt: new Date().toISOString(),
    };

    if (input.includeVideoMetadata === false) {
        for (const k of ['channelName', 'channelUrl', 'description', 'viewCount', 'likeCount', 'publishDate', 'duration', 'thumbnailUrl']) {
            delete (result as any)[k];
        }
    }

    incrementItems();
    await Actor.pushData(result);
    const state = getState();
    log.info(`[${state.itemsScraped}/${maxItems || '∞'}] "${metadata.title}" (${segments.length} segs, ${track.languageCode}${track.kind === 'asr' ? ' auto' : ''})`);
    await Actor.setStatusMessage(`Scraped ${state.itemsScraped} transcripts`);
});

// --- PLAYLIST handler ---
router.addHandler(LABELS.PLAYLIST, async ({ request, $, log, session, crawler }) => {
    checkForBlock($, session);
    const data = extractInitialData($ as any);
    if (!data) { log.warning(`No playlist data: ${request.url}`); return; }
    const ids = extractPlaylistVideoIds(data);
    log.info(`Found ${ids.length} videos in playlist`);
    await crawler.addRequests(ids.map((id: string) => ({ url: `${YOUTUBE.VIDEO_URL}${id}`, label: LABELS.VIDEO, uniqueKey: `video-${id}` })));
});

// --- CHANNEL handler ---
router.addHandler(LABELS.CHANNEL, async ({ request, $, log, session, crawler }) => {
    checkForBlock($, session);
    const data = extractInitialData($ as any);
    if (!data) { log.warning(`No channel data: ${request.url}`); return; }
    const ids = extractChannelVideoIds(data);
    log.info(`Found ${ids.length} videos on channel`);
    await crawler.addRequests(ids.map((id: string) => ({ url: `${YOUTUBE.VIDEO_URL}${id}`, label: LABELS.VIDEO, uniqueKey: `video-${id}` })));
});

// --- SEARCH handler ---
router.addHandler(LABELS.SEARCH, async ({ request, $, log, session, crawler }) => {
    checkForBlock($, session);
    const data = extractInitialData($ as any);
    if (!data) { log.warning(`No search data: ${request.url}`); return; }
    const ids = extractSearchVideoIds(data);
    log.info(`Found ${ids.length} videos for "${request.userData.searchTerm}"`);
    await crawler.addRequests(ids.map((id: string) => ({ url: `${YOUTUBE.VIDEO_URL}${id}`, label: LABELS.VIDEO, uniqueKey: `video-${id}` })));
});
