import { Actor, Log } from 'apify';
import { Request, BasicCrawler } from 'crawlee';
import { LABELS, YOUTUBE, PATTERNS } from './constants.js';
import {
    fetchTranscriptData,
    extractInitialData,
    extractCaptionTracks,
    extractVideoMetadata,
    selectCaptionTrack,
    parseTranscriptXml,
    segmentsToPlainText,
    segmentsToSrt,
    segmentsToVtt,
    extractPlaylistVideoIds,
    extractSearchVideoIds,
    extractChannelVideoIds,
} from './extractors.js';
import { getState, incrementItems, hasReachedLimit, isDuplicate } from './state.js';
import { Input, OutputItem, TranscriptSegment } from './types.js';

let actorInput: Input = {};
export function setActorInput(input: Input): void { actorInput = input; }

function buildErrorOutput(url: string, videoId: string, title: string | null, errorMessage: string) {
    return {
        url, videoId, title, channelName: null, channelUrl: null, description: null,
        viewCount: null, likeCount: null, publishDate: null, duration: null, thumbnailUrl: null,
        language: actorInput.language ?? 'en', languageName: '', isAutoGenerated: false,
        isTranslated: false, availableLanguages: [] as string[], transcript: null, fullText: null,
        formattedTranscript: null, segmentCount: 0, totalDurationSecs: 0,
        '#isFailed': true, '#errorMessage': errorMessage,
        scrapedAt: new Date().toISOString(),
    };
}

/**
 * VIDEO handler — no web page fetch needed.
 * Uses InnerTube API directly for metadata + transcript.
 */
export async function handleVideo(request: Request, log: Log): Promise<void> {
    const input = actorInput;
    const maxItems = input.maxItems ?? 0;
    if (hasReachedLimit(maxItems)) return;

    const videoId = request.url.match(PATTERNS.VIDEO_ID)?.[1];
    if (!videoId) { log.warning(`No video ID in ${request.url}`); return; }
    if (isDuplicate(videoId)) { log.debug(`Duplicate: ${videoId}`); return; }

    const lang = input.language ?? 'en';
    const includeAuto = input.includeAutoGenerated !== false;

    // Single call: InnerTube API + transcript fetch on same proxy IP
    const { playerResponse, transcriptXml } = await fetchTranscriptData(videoId, lang, includeAuto);

    if (!playerResponse) {
        log.warning(`No player response for ${videoId}`);
        incrementItems();
        await Actor.pushData(buildErrorOutput(request.url, videoId, null, 'Video unavailable'));
        return;
    }

    const status = playerResponse.playabilityStatus?.status;
    if (status === 'LOGIN_REQUIRED' || status === 'ERROR' || status === 'UNPLAYABLE') {
        const reason = playerResponse.playabilityStatus?.reason ?? status;
        log.warning(`Video ${videoId}: ${reason}`);
        incrementItems();
        await Actor.pushData(buildErrorOutput(request.url, videoId, playerResponse.videoDetails?.title ?? null, reason));
        return;
    }

    const metadata = input.includeVideoMetadata !== false
        ? extractVideoMetadata(playerResponse)
        : { title: playerResponse.videoDetails?.title ?? null, channelName: null, channelUrl: null, description: null, viewCount: null, likeCount: null, publishDate: null, duration: null, thumbnailUrl: null };

    const captionTracks = extractCaptionTracks(playerResponse);
    const availableLanguages = captionTracks.map((t: any) => `${t.languageCode}${t.kind === 'asr' ? ' (auto)' : ''}`);
    const track = selectCaptionTrack(captionTracks, lang, includeAuto);

    let segments: TranscriptSegment[] = [];
    if (transcriptXml) {
        segments = parseTranscriptXml(transcriptXml);
    } else if (captionTracks.length > 0) {
        log.warning(`Empty transcript for ${videoId}`);
    }

    const fmt = input.outputFormat ?? 'json';
    let formattedTranscript: string | null = null;
    if (fmt === 'srt') formattedTranscript = segmentsToSrt(segments);
    else if (fmt === 'vtt') formattedTranscript = segmentsToVtt(segments);

    const totalDur = segments.length > 0 ? segments[segments.length - 1].start + segments[segments.length - 1].duration : 0;

    const result: OutputItem = {
        url: request.url, videoId, ...metadata,
        language: track?.languageCode ?? lang,
        languageName: track?.name ?? '',
        isAutoGenerated: track?.kind === 'asr' || false,
        isTranslated: false,
        availableLanguages,
        transcript: fmt === 'json' ? segments : null,
        fullText: segmentsToPlainText(segments),
        formattedTranscript,
        segmentCount: segments.length,
        totalDurationSecs: Math.round(totalDur),
        scrapedAt: new Date().toISOString(),
    };

    if (input.includeVideoMetadata === false) {
        for (const k of ['channelName', 'channelUrl', 'description', 'viewCount', 'likeCount', 'publishDate', 'duration', 'thumbnailUrl']) {
            delete (result as any)[k];
        }
    }

    incrementItems();
    await Actor.pushData(result);
    const state = getState();
    log.info(`[${state.itemsScraped}/${maxItems || '∞'}] "${metadata.title}" (${segments.length} segs, ${track?.languageCode ?? 'none'}${track?.kind === 'asr' ? ' auto' : ''})`);
    await Actor.setStatusMessage(`Scraped ${state.itemsScraped} transcripts`);
}

/** PLAYLIST handler — needs HTML page */
export async function handlePlaylist(request: Request, $: any, log: Log, crawler: BasicCrawler): Promise<void> {
    const data = extractInitialData($);
    if (!data) { log.warning(`No playlist data: ${request.url}`); return; }
    const ids = extractPlaylistVideoIds(data);
    log.info(`Found ${ids.length} videos in playlist`);
    await crawler.addRequests(ids.map((id: string) => ({ url: `${YOUTUBE.VIDEO_URL}${id}`, label: LABELS.VIDEO, uniqueKey: `video-${id}` })));
}

/** CHANNEL handler — needs HTML page */
export async function handleChannel(request: Request, $: any, log: Log, crawler: BasicCrawler): Promise<void> {
    const data = extractInitialData($);
    if (!data) { log.warning(`No channel data: ${request.url}`); return; }
    const ids = extractChannelVideoIds(data);
    log.info(`Found ${ids.length} videos on channel`);
    await crawler.addRequests(ids.map((id: string) => ({ url: `${YOUTUBE.VIDEO_URL}${id}`, label: LABELS.VIDEO, uniqueKey: `video-${id}` })));
}

/** SEARCH handler — needs HTML page */
export async function handleSearch(request: Request, $: any, log: Log, crawler: BasicCrawler): Promise<void> {
    const data = extractInitialData($);
    if (!data) { log.warning(`No search data: ${request.url}`); return; }
    const ids = extractSearchVideoIds(data);
    log.info(`Found ${ids.length} videos for "${request.userData.searchTerm}"`);
    await crawler.addRequests(ids.map((id: string) => ({ url: `${YOUTUBE.VIDEO_URL}${id}`, label: LABELS.VIDEO, uniqueKey: `video-${id}` })));
}
