export interface Input {
    startUrls?: { url: string; [key: string]: unknown }[];
    searchTerms?: string[];
    videoIds?: string[];
    maxItems?: number;
    maxConcurrency?: number;
    language?: string;
    includeAutoGenerated?: boolean;
    includeTimestamps?: boolean;
    outputFormat?: 'json' | 'plaintext' | 'srt' | 'vtt';
    includeVideoMetadata?: boolean;
    translationLanguage?: string;
    debugMode?: boolean;
    proxyConfig?: {
        useApifyProxy?: boolean;
        apifyProxyGroups?: string[];
        apifyProxyCountry?: string;
    };
}

export interface CaptionTrack {
    baseUrl: string;
    languageCode: string;
    name: string;
    kind?: string; // 'asr' = auto-generated
    isTranslatable?: boolean;
}

export interface TranscriptSegment {
    text: string;
    start: number;      // seconds
    duration: number;    // seconds
}

export interface OutputItem {
    url: string;
    videoId: string;
    title: string | null;
    channelName: string | null;
    channelUrl: string | null;
    description: string | null;
    viewCount: number | null;
    likeCount: number | null;
    publishDate: string | null;
    duration: string | null;
    thumbnailUrl: string | null;
    language: string;
    languageName: string;
    isAutoGenerated: boolean;
    isTranslated: boolean;
    availableLanguages: string[];
    transcript: TranscriptSegment[] | null;
    fullText: string | null;
    formattedTranscript: string | null;  // SRT or VTT format
    segmentCount: number;
    totalDurationSecs: number;
    scrapedAt: string;
}

export interface CrawlState {
    itemsScraped: number;
}
